[pytest]

markers = 
    smoke: Smoke Testing Test Cases
    regression: Regresion testing Test Cases
    test:  Test env test cases
    prod:   Prod env test cases
    uat: UAT Test Cases
    dh: Data Handling Test Cases
    